version: '3.7'

services:
  mlserver:
    build:
      context: .
      dockerfile: Dockerfile.mlserver
    ports:
      - "5555:5555"
    volumes:
      - ./mlserver:/mlserver  # Mount local directory ./mlserver to container's /mlserver directory
    working_dir: /mlserver  # Set the working directory in the container
    entrypoint: ["mlserver", "start", "."]  # Set entrypoint to mlserver start .
    env_file:
      - .env
    environment:
      - MLFLOW_S3_ENDPOINT_URL=http://minio:9000
      - MLFLOW_TRACKING_URI=http://mlflow_server:5000
